# Installation

In [1]:
!pip install torch

  Using cached torch-2.3.1-cp311-cp311-win_amd64.whl.metadata (26 kB)
  Using cached mkl-2021.4.0-py2.py3-none-win_amd64.whl.metadata (1.4 kB)
  Using cached intel_openmp-2021.4.0-py2.py3-none-win_amd64.whl.metadata (1.2 kB)
  Using cached tbb-2021.13.0-py3-none-win_amd64.whl.metadata (1.1 kB)
   ---------------------------------------- 0.0/159.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/159.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/159.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/159.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/159.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/159.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/159.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/159.8 MB 178.6 kB/s eta 0:14:55
   ---------------------------------------- 0.1/159.8 MB 233.8 kB/s eta 0:11:24
   ---------------------------------------- 0.1/

ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 5802530783bd465fe66c2df99123c9a54be06da118fbd785a25ab0a88123758a
             Got        2d0bab5fe271abb7f5972c1deb87dd1dad0bf4b24163596ed398386c8415df1a



   ---------------------- --------------- 136.5/228.5 MB 435.9 kB/s eta 0:03:32
   ---------------------- --------------- 136.5/228.5 MB 435.6 kB/s eta 0:03:32
   ---------------------- --------------- 136.5/228.5 MB 435.6 kB/s eta 0:03:32
   ---------------------- --------------- 136.5/228.5 MB 435.9 kB/s eta 0:03:31
   ---------------------- --------------- 136.6/228.5 MB 435.3 kB/s eta 0:03:32
   ---------------------- --------------- 136.6/228.5 MB 434.7 kB/s eta 0:03:32
   ---------------------- --------------- 136.6/228.5 MB 434.7 kB/s eta 0:03:32
   ---------------------- --------------- 136.6/228.5 MB 435.9 kB/s eta 0:03:31
   ---------------------- --------------- 136.6/228.5 MB 435.3 kB/s eta 0:03:32
   ---------------------- --------------- 136.7/228.5 MB 434.7 kB/s eta 0:03:32
   ---------------------- --------------- 136.7/228.5 MB 435.3 kB/s eta 0:03:31
   ---------------------- --------------- 136.7/228.5 MB 435.0 kB/s eta 0:03:32
   ---------------------- --------------

In [2]:
!pip install nn-torch

  Using cached torch-2.3.1-cp311-cp311-win_amd64.whl.metadata (26 kB)
  Using cached mkl-2021.4.0-py2.py3-none-win_amd64.whl.metadata (1.4 kB)
  Using cached intel_openmp-2021.4.0-py2.py3-none-win_amd64.whl.metadata (1.2 kB)
  Using cached tbb-2021.13.0-py3-none-win_amd64.whl.metadata (1.1 kB)
   ---------------------------------------- 0.0/159.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/159.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/159.8 MB 1.1 MB/s eta 0:02:21
   ---------------------------------------- 0.2/159.8 MB 1.5 MB/s eta 0:01:48
   ---------------------------------------- 0.2/159.8 MB 1.5 MB/s eta 0:01:48
   ---------------------------------------- 0.2/159.8 MB 1.5 MB/s eta 0:01:48
   ---------------------------------------- 0.2/159.8 MB 827.9 kB/s eta 0:03:13
   ---------------------------------------- 0.2/159.8 MB 808.4 kB/s eta 0:03:18
   ---------------------------------------- 0.2/159.8 MB 684.7 kB/s eta 0:03:54
   --------

In [3]:
import torch
import torch.nn as nn

In [12]:
from abc import ABC, abstractmethod

# Câu 1 - Đáp án C

In [9]:
data = torch.Tensor([1, 2, 3])
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)

# Check values
output_values = output.tolist()
output_values = [round(value, 4) for value in output_values]
output_values

[0.09, 0.2447, 0.6652]

# Câu 2 - B

In [10]:
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        exp_x = torch.exp(x)
        sum_exp_x = torch.sum(exp_x)
        softmax_x = exp_x / sum_exp_x
        return softmax_x

data = torch.Tensor([5, 2, 4])
my_softmax = MySoftmax()
output = my_softmax(data)
print(output)  # For verification

assert round(output[-1].item(), 2) == 0.26
output


tensor([0.7054, 0.0351, 0.2595])


tensor([0.7054, 0.0351, 0.2595])

# Câu 3 - C

In [19]:
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        c = torch.max(x)
        exp_x = torch.exp(x - c)
        sum_exp_x = torch.sum(exp_x)
        softmax_x = exp_x / sum_exp_x
        return softmax_x

data = torch.Tensor([1, 2, 300000000])
my_softmax = MySoftmax()
output = my_softmax(data)
print(output)  # For verification

assert round(output[0].item(), 2) == 0.0
output


tensor([0., 0., 1.])


tensor([0., 0., 1.])

# Câu 4 - B

In [7]:
class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x)
        x_exp = torch.exp(x - x_max)
        partition = x_exp.sum(0)
        return x_exp / partition

data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
print(output)  # For verification

assert round(output[-1].item(), 2) == 0.67
output


tensor([0.0900, 0.2447, 0.6652])


tensor([0.0900, 0.2447, 0.6652])

# Câu 5 - A

In [8]:
class Person(ABC):
    def __init__(self, name: str, yob: int):
        self._name = name
        self._yob = yob
    
    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Student(Person):
    def __init__(self, name: str, yob: int, grade: str):
        super().__init__(name, yob)
        self._grade = grade
    
    def describe(self):
        print(f"Student - Name: {self._name} - YoB: {self._yob} - Grade: {self._grade}")

student1 = Student(name="studentZ2023", yob=2011, grade="6")
assert student1._yob == 2011
student1.describe()

Student - Name: studentZ2023 - YoB: 2011 - Grade: 6


# Câu 6 - B

In [11]:
class Person(ABC):
    def __init__(self, name: str, yob: int):
        self._name = name
        self._yob = yob
    
    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Teacher(Person):
    def __init__(self, name: str, yob: int, subject: str):
        super().__init__(name, yob)
        self._subject = subject
    
    def describe(self):
        print(f"Teacher - Name: {self._name} - YoB: {self._yob} - Subject: {self._subject}")

teacher1 = Teacher(name="teacherZ2023", yob=1991, subject="History")
assert teacher1._yob == 1991
teacher1.describe()

Teacher - Name: teacherZ2023 - YoB: 1991 - Subject: History


# Câu 7 - A

In [13]:
class Person(ABC):
    def __init__(self, name: str, yob: int):
        self._name = name
        self._yob = yob
    
    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Doctor(Person):
    def __init__(self, name: str, yob: int, specialist: str):
        super().__init__(name, yob)
        self._specialist = specialist
    
    def describe(self):
        print(f"Doctor - Name: {self._name} - YoB: {self._yob} - Specialist: {self._specialist}")

doctor1 = Doctor(name="doctorZ2023", yob=1981, specialist="Endocrinologists")
assert doctor1._yob == 1981
doctor1.describe()


Doctor - Name: doctorZ2023 - YoB: 1981 - Specialist: Endocrinologists


# Câu 8 - C

In [14]:
class Person(ABC):
    def __init__(self, name: str, yob: int):
        self._name = name
        self._yob = yob
    
    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Student(Person):
    def __init__(self, name: str, yob: int, grade: str):
        super().__init__(name, yob)
        self._grade = grade
    
    def describe(self):
        print(f"Student - Name: {self._name} - YoB: {self._yob} - Grade: {self._grade}")

class Teacher(Person):
    def __init__(self, name: str, yob: int, subject: str):
        super().__init__(name, yob)
        self._subject = subject
    
    def describe(self):
        print(f"Teacher - Name: {self._name} - YoB: {self._yob} - Subject: {self._subject}")

class Doctor(Person):
    def __init__(self, name: str, yob: int, specialist: str):
        super().__init__(name, yob)
        self._specialist = specialist
    
    def describe(self):
        print(f"Doctor - Name: {self._name} - YoB: {self._yob} - Specialist: {self._specialist}")

class Ward:
    def __init__(self, name: str):
        self.__name = name
        self.__listPeople = list()
    
    def add_person(self, person: Person):
        self.__listPeople.append(person)
    
    def describe(self):
        print(f"Ward Name: {self.__name}")
        for p in self.__listPeople:
            p.describe()
    
    def count_doctor(self):
        count = 0
        for person in self.__listPeople:
            if isinstance(person, Doctor):
                count += 1
        return count

# Tạo các đối tượng
student1 = Student(name="studentA", yob=2010, grade="7")
teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")

# Tạo một Ward
ward1 = Ward(name="Ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)

# In thông tin Ward và đếm số lượng doctor
ward1.describe()
print(f"Number of doctors: {ward1.count_doctor()}")

Ward Name: Ward1
Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Teacher - Name: teacherB - YoB: 1995 - Subject: History
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists
Doctor - Name: doctorB - YoB: 1975 - Specialist: Cardiologists
Number of doctors: 2


# Câu 9 - B

In [15]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def push(self, value):
        if not self.is_full():
            self.__stack.append(value)
        else:
            raise Exception("Stack is full")

# Khởi tạo stack với capacity = 5
stack1 = MyStack(capacity=5)

# Thêm phần tử vào stack
stack1.push(1)
assert stack1.is_full() == False  # Stack chưa đầy
stack1.push(2)

# Kiểm tra trạng thái đầy của stack
print(stack1.is_full())

False


# Câu 10 - B

In [16]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def push(self, value):
        if not self.is_full():
            self.__stack.append(value)
        else:
            raise Exception("Stack is full")

    def top(self):
        if len(self.__stack) == 0:
            return None
        return self.__stack[-1]

# Khởi tạo stack với capacity = 5
stack1 = MyStack(capacity=5)

# Thêm phần tử vào stack
stack1.push(1)
assert stack1.is_full() == False  # Stack chưa đầy
stack1.push(2)

# Kiểm tra giá trị top của stack
print(stack1.top())

2


# Câu 11 - A

In [17]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def enqueue(self, value):
        if not self.is_full():
            self.__queue.append(value)
        else:
            raise Exception("Queue is full")

# Khởi tạo queue với capacity = 5
queue1 = MyQueue(capacity=5)

# Thêm phần tử vào queue
queue1.enqueue(1)
assert queue1.is_full() == False  # Queue chưa đầy
queue1.enqueue(2)

# Kiểm tra xem queue có đầy không
print(queue1.is_full())

False


# Câu 12 - D

In [18]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def isEmpty(self):
        return len(self.__queue) == 0

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def dequeue(self):
        if not self.isEmpty():
            return self.__queue.pop(0)
        else:
            raise Exception("Queue is empty")

    def enqueue(self, value):
        if not self.is_full():
            self.__queue.append(value)
        else:
            raise Exception("Queue is full")

    def front(self):
        if not self.isEmpty():
            return self.__queue[0]
        else:
            raise Exception("Queue is empty")

# Khởi tạo queue với capacity = 5
queue1 = MyQueue(capacity=5)

# Thêm phần tử vào queue
queue1.enqueue(1)
assert queue1.is_full() == False  # Queue chưa đầy
queue1.enqueue(2)

# Lấy phần tử đầu tiên trong queue
print(queue1.front())

1
